version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: woovibank_mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=woovi-bank
    restart: always
